version: '3.7'
services:
    nginx:
        image: nginx:1.18
        networks:
            - wp_net
        volumes:
            - ./nginx_server:/etc/nginx/conf.d:ro
            - front_code:/usr/share/nginx/html
        depends_on: 
            - front_dev
            - socketserver
        links:
            - front_dev
            - socketserver
        ports:
            - 8080:80
        environment:
            SOCKET_SERVER: socketserver:8888

    socketserver:
        build:
            context: ./backend_socket_server
            dockerfile: Dockerfile
        volumes:
            - ./backend_socket_server/templates:/templates
        environment: 
            CORS_ALLOWED: http://localhost:8080
            HOST: 0.0.0.0
            PORT: 8888
        expose:
            - "8888"
        networks:
            - wp_net

    front_dev:
        build:
            context: ./frontend
        volumes:
            - front_code:/dist
        command: /bin/cp -rTf /app/app /dist

    

networks:
    wp_net:
        driver: bridge

volumes:
    front_code:
        driver: local