version: '3.7'
services:
    nginx:
        image: nginx:1.18
        volumes:
            - ./nginx_server:/etc/nginx/conf.d:ro
            - front_code:/usr/share/nginx/html
        depends_on: 
            - front_dev
            - socketserver
        links:
            - front_dev
            - socketserver
        ports:
            - 8080:80
        environment:
            SOCKET_SERVER: socketserver:${API_SERVER_PORT}

    socketserver:
        build:
            context: ./backend_socket_server
            dockerfile: Dockerfile
        volumes:
            - ./backend_socket_server/templates:/templates
        environment: 
            CORS_ALLOWED: "*"
            HOST: 0.0.0.0
            PORT: ${API_SERVER_PORT}
            DB_SERVER_URL: "mysql://${DB_USER_NAME}:${DB_USER_PASSWORD}@db:${DB_SQL_PORT}/ase_database"
        expose:
            - ${API_SERVER_PORT}
        depends_on: 
            - db


    front_dev:
        build:
            context: ./frontend
        volumes:
            - front_code:/dist
        command: /bin/cp -rTf /app/app /dist 
    
    db:
        image: mysql:5.7
        container_name: "ase_database"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ase_database
            MYSQL_USER: ${DB_USER_NAME}
            MYSQL_PASSWORD: ${DB_USER_PASSWORD}
        volumes:
            - database:/var/lib/mysql
            - ./db/conf.d/:/etc/mysql/conf.d/
            - database_log:/var/log/mysql/
        expose:
            - ${DB_SQL_PORT}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=db
            - PMA_USER=root
            - PMA_PASSWORD=${DB_ROOT_PASSWORD}
        ports:
            - 8081:80

volumes:
    front_code:
        driver_opts: 
            type: none
            device: ./frontend/app
            o: bind

    database:
        driver: local

    database_log:
        driver: local